# base image
FROM python:3.8.6-buster

# streamlit-specific commands
RUN mkdir -p /root/.streamlit
RUN bash -c 'echo -e "\
[general]\n\
email = \"\"\n\
" > /root/.streamlit/credentials.toml'
RUN bash -c 'echo -e "\
[server]\n\
enableCORS = false\n\
" > /root/.streamlit/config.toml'

# exposing default port for streamlit
#EXPOSE 8501

COPY UI /UI
COPY requirements.txt  /requirements.txt
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt

# CMD streamlit run UI/serpV2.py --server.port 8000
ENTRYPOINT ["streamlit", "run", "UI/serpV2.py", "--server.port=8080", "--server.address=0.0.0.0"]
